//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class journalEntities : DbContext
    {
        public journalEntities()
            : base("name=journalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_user> app_user { get; set; }
        public virtual DbSet<place> place { get; set; }
        public virtual DbSet<review> review { get; set; }
        public virtual DbSet<reviewcomment> reviewcomment { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<user_profile> user_profile { get; set; }
    }
}
