//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviewcomment
    {
        public int reviewcomment_id { get; set; }
        public string text { get; set; }
        public int mark { get; set; }
        public int review_id { get; set; }
        public int user_id { get; set; }
    
        public virtual app_user app_user { get; set; }
    }
}
