//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExcelStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rest.Resources.ExcelStringResources", typeof(ExcelStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average mark.
        /// </summary>
        internal static string AverageMarkHeader {
            get {
                return ResourceManager.GetString("AverageMarkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityHeader {
            get {
                return ResourceManager.GetString("CityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average mark for places.
        /// </summary>
        internal static string IntroPlacesStatistics {
            get {
                return ResourceManager.GetString("IntroPlacesStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places yet.
        /// </summary>
        internal static string NoPlacesMessage {
            get {
                return ResourceManager.GetString("NoPlacesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Name.
        /// </summary>
        internal static string PlaceNameHeader {
            get {
                return ResourceManager.GetString("PlaceNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacesStatistics.xlsx.
        /// </summary>
        internal static string PlacesStatisticsFileName {
            get {
                return ResourceManager.GetString("PlacesStatisticsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Type.
        /// </summary>
        internal static string PlaceTypeHeader {
            get {
                return ResourceManager.GetString("PlaceTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewStatistics.xlsx.
        /// </summary>
        internal static string ReviewStatisticsFileName {
            get {
                return ResourceManager.GetString("ReviewStatisticsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string StreetHeader {
            get {
                return ResourceManager.GetString("StreetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some.
        /// </summary>
        internal static string WorkSheetName {
            get {
                return ResourceManager.GetString("WorkSheetName", resourceCulture);
            }
        }
    }
}
